---
- name: Openshift IPI Teardown
  user: ansible
  hosts: localhost
  connection: local
  gather_facts: false
  module_defaults:
    get_url:
      timeout: 60
  vars_files:
  - ocp
  roles:
  - role: openshift-ipi-teardown
