apiVersion: argoproj.io/v1alpha1
kind: ArgoCD
metadata:
  name: argocd
  namespace: openshift-operators
spec:
  server:
    resources:
      limits:
        cpu: 500m
        memory: 256Mi
      requests:
        cpu: 125m
        memory: 128Mi
    route:
      enabled: true
  grafana:
    route:
      enabled: true
    enabled: true
  prometheus:
    route:
      enabled: true
    enabled: true
  rbac:
    defaultPolicy: 'role:app-admin'
    policy: |
      p, role:app-admin, applications, *, */*, allow
      g, system:cluster-admins, role:admin
    scopes: '[groups]'
  repo:
    resources:
      limits:
        cpu: 1000m
        memory: 1024Mi
      requests:
        cpu: 250m
        memory: 256Mi
  dex:
    resources:
      limits:
        cpu: 500m
        memory: 256Mi
      requests:
        cpu: 250m
        memory: 128Mi
    openShiftOAuth: true
  initialSSHKnownHosts:
    excludedefaulthosts: true
    keys: |
      [gitserver]:7999 ssh-rsa ...
      [gitserver.acme.com]:7999 ...
  repositoryCredentials: |
    - sshPrivateKeySecret:
        key: sshPrivateKey
        name: private-key
      type: git
      url: ssh://git@gitserver.acme.com:7999/
  ha:
    resources:
      limits:
        cpu: 500m
        memory: 256Mi
      requests:
        cpu: 250m
        memory: 128Mi
    enabled: true
  redis:
    resources:
      limits:
        cpu: 500m
        memory: 256Mi
      requests:
        cpu: 250m
        memory: 128Mi
  controller:
    resources:
      limits:
        cpu: 2000m
        memory: 2048Mi
      requests:
        cpu: 250m
        memory: 1024Mi
    sharding:
      enabled: true
      replicas: 3
    appSync: 3m
    logFormat: json
  statusBadgeEnabled: true