server: true
server_cpu_limit: 500m
server_mem_limit: 500Mi
server_cpu_request: 200m
server_mem_request: 200Mi
server_route: true
grafana: true
grafana_route: true
prometheus: true
prometheus_route: true
ssh_git_url: gitserver.acme.com:7999
repo_pub_ssh_key_file: keys/key.pub
repo_pvt_ssh_key_file: keys/key